name: Workflow 2

on:
  workflow_dispatch:
    inputs:
      # Environment to run against (staging or production).
      environment:
        description: "Environment to run against"
        required: true
        type: environment
        default: "staging"
      dry-run:
        description: "Dry run"
        required: true
        type: boolean
        default: false
      destroy-subscriptions:
        description: "Destroy subscriptions"
        required: false
        type: string
jobs:

  build:
    name: Subscriptions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v3

    - name: Show input values
      run: |
        if [ "${{ github.event.inputs.destroy-subscriptions }}" != '' ]; then
        echo "Subscriptions: ${{ github.event.inputs.destroy-subscriptions }}"
    
    outputs:
      subs: ${{ github.event.inputs.destroy-subscriptions }} || 'Null'

  Show:
    needs: [build]
    name: Show input subscription
    runs-on: ubuntu-latest
    steps:
    - name: Showing subscription entered
      run: |
        echo "Subscriptions: ${{ needs.build.outputs.subs }}"
