name: Worflow dispatch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      subscriptions:
        description: "Subscriptions"
        required: true
        type: string
        default: "value 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout latest commit

    - name: Show input values
      run: |
        echo "Subscriptions: {{ github.event.inputs.subscriptions }}"
