name: Worflow dispatch

on:
  workflow_dispatch:
    inputs:
      subscriptions:
        description: "Subscriptions"
        required: true
        type: string
        default: "[]"

jobs:

  build:
    name: Subscriptions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v3

    - name: Show input values
      run: |
        echo "Subscriptions: ${{ toJson(github.event.inputs.subscriptions) }}"
    outputs:
      subscriptions: ${{ toJson(github.event.inputs.subscriptions) }}
      subs: '["Nestor","Other"]'

  example_of_matrix:
    needs: [build]
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        subscription: ${{ fromJson(needs.build.outputs.subs) }}
    steps:
      - run: |
          echo "${{ matrix.subscription }}"

  example_of_matrix2:
    needs: [build]
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        subscription: ${{ needs.build.outputs.subs }}
    steps:
      - run: |
          echo "${{ matrix.subscription }}"
  
        
      
