name: Worflow dispatch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      subscriptions:
        description: "Destroy or apply changes to subscriptions"
        required: true
        type: string
        default: "value 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Chackout latest commit

    - name: Show input values
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
